defaults:
  - sft_stage2
  - /wandb: ar1_stage2
  - _self_

data:
  train_dataset:
    chunk_ids: "0-186"
  val_dataset:
    chunk_ids: "186-205"

model:
  pretrained_model_name_or_path: /data/achahe/alpasim/huggingface/hub/models--nvidia--Alpamayo-R1-10B/snapshots/d72c6a2757b10cacb69b688ca66ccfad3dafbf37
  dtype: bfloat16

trainer:
  report_to: wandb

paths:
  output_dir: /data/achahe/alpamayo-recipes/recipes/alpamayo1_sft/training/output_stage2_ar1

evaluate:
  eval_ckpt: null
